- .github/pull_request_template.md
added a pull request template.
The markdown can be tested with this tool: https://dillinger.io/
I'm not completly sure that this will use the template on github. it's hard to test without having it in master ^^ however i followed [this guide](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) which should verify that this does in fact work. 
- Added pull request template
- [HCLANG-1](http://hcl.codes/jira/browse/HCLANG-1)
> initial test fix

- README.md
- code/.idea/idea-code-style.xml
- code/.idea/inspekt.xml
- code/build.gradle
- code/default-detekt-config.yml
- code/src/main/kotlin/Main.kt
- code/src/main/kotlin/lexer/ILexer.kt
- code/src/main/kotlin/lexer/Lexer.kt
- code/src/test/kotlin/SimpleTest.kt
- code/src/test/kotlin/lexicalTests/LexerTest.kt
CI has been set up as initially expected
- Added code coverage
- Added artifacts in teamcity
- More configuration to Dokka
- Made sample lexer class with test to ensure CI works as expected. These should later be removed for obvious reasons.
- HCLANG-10 …
> Hclang 10 - CI has been setup as initially expected

- misc/email_til.gymnasier.txt
A template that can be used to send to gymnasiums.
- created a single file as a basis for emails to the different gymnasiums
- HCLANG-17
- Are there testcases for new features / methods?
- Have you tried running the source and tested things that …
> Jira id: HCLANG-17 - #comment wrote template mail

- report/2.Analysis/0.AnalysisCtrl.tex
- report/2.Analysis/EducationalMiniComputers.tex
- report/2.Analysis/LanguagesForYoungPeople.tex
- report/bibtex/litteratur.bib
Added some analysis of small mini computers, and why they have become popular for educational purposes.
- Added some analysis of small mini computers, and why they have become popular for educational purposes.
- HCLANG-22
- Are there testcases for …
> Hclang 22 educational mini computers

- report/preamb.tex
Removed bibpunct
- Removed bibpunct
> Remove bibpunct - which is harvard specific. We use ieeetran

- report/1.Introduction/0.PrefaceCtrl.tex
Created preface for project and started a terms list
- Preface added
- Termslist added
- HCLANG-18
- HCLANG-20
- Are there testcases for new features / methods?
- Have you tried running …
> Added preface chapter

- report/2.Analysis/ArduinoLanguagesCtrl.tex
Added a section for existing arduino languages to the report. It is written in its own file. It isn't currently referenced by main.tex
- Added the ArduinoLanguagesCtrl.tex file to report under analysis
- HCLANG-25
- Are there testcases for new …
> First draft of existing language subsection

- report/2.Analysis/0.AnalysisCtrl.tex
Added the arduino langauge section to the report.
- Added the arduino langauge section to the report.
- HCLANG-32
- Are there testcases for new features / methods?
- Have you tried running the source and tested things that cannot be test-cased?
- …
> Jira id: HCLANG-32 - #comment Added the arduino language section

- report/2.Analysis/0.AnalysisCtrl.tex
- report/2.Analysis/HighOrderFunctions.tex
Described high-order functions, and their reasoning for being present within HCL
Described high-order functions, and their reasoning for being present within HCL
- HCLANG-31
- Are public methods …
> Hclang 31 highorder functions

- code/build.gradle
- code/src/main/kotlin/lexer/Tokens.kt
- code/src/test/kotlin/lexicalTests/TokenTest.kt
Implemented initial tokens for the lexer
- Added token classes for the lexer
- Added some tests to ensure basic functionality works, but primarily for code coverage.
- HCLANG-48
- Are public methods …
> Hclang 48 lexical tokens

- .gitignore
- code/build.gradle
- code/src/main/kotlin/Main.kt
- code/src/main/kotlin/exceptions/CompilationException.kt
- code/src/main/kotlin/exceptions/LexerException.kt
- code/src/main/kotlin/exceptions/ParserException.kt
- code/src/main/kotlin/lexer/ILexer.kt
- code/src/main/kotlin/lexer/Lexer.kt
- code/src/main/kotlin/lexer/PositionalToken.kt
- code/src/main/kotlin/lexer/Tokens.kt
- code/src/main/kotlin/logger/ILogger.kt
- code/src/main/kotlin/logger/Logger.kt
- code/src/main/kotlin/parser/AbstractSyntaxTree.kt
- code/src/main/kotlin/parser/IParser.kt
- code/src/test/kotlin/lexicalTests/LexerTest.kt
- code/src/test/kotlin/lexicalTests/TokenTest.kt
- code/src/test/kotlin/loggerTests/LoggerTest.kt
Initial implementation of interfaces and solution structure. Tried to comply as much as possible with the predetermined structure. However, minor modifications were made so @C0DK  should have a look. If something seems strange let me know.
- Modified code coverage values a bit. Branch coverage of 0.8 was too much for now. Maybe it can be increased later, when more code has been implemented.
- Added compilationErrorException with Parser and Lexer implementation
- Added ILexer interface
- Added IParser interface
- Added a ILogger interface a long with a VERY simple implementation
- Made initial simple tests for both lexer, and logger (logger primarily for coverage for now. But actual test can and should be made later)
- HCLANG-46
A small checklist of things to note when you are doing a …
> Hclang 46 initial interfaces

- report/1.Introduction/0.PrefaceCtrl.tex
- report/1.Introduction/1.IntroductionCtrl.tex
- report/2.Analysis/0.AnalysisCtrl.tex
- report/2.Analysis/ArduinoLanguagesCtrl.tex
- report/2.Analysis/EducationalMiniComputers.tex
- report/2.Analysis/HighOrderFunctions.tex
- report/2.Analysis/LanguagesForYoungPeople.tex
- report/2.Analysis/ProblemStatement.tex
- report/2.Analysis/Scope.tex
Added comments, added line to HOF explaining it is meant to introduce, moved problem statement to own file.
Solved HCLANG-51, add comments
- Added preliminary internal comments to all existing sections
- Moved problem statement to own file
- Added line to High-Order functions further
-
- HCLANG-51
- Make …
> Added comments, added line to HOF, moved problem statement to own file

- code/build.gradle
- code/src/main/kotlin/parser/AbstractSyntaxTree.kt
Added the initial AST structure. Would be surprised if this is going to be final, but for now this AST structure should work to get us started.
- Added the initial AST structure
- HCLANG-57
- Are …
> Hclang 57 create ast classes

- report/3.Theory/LanguageSpecification.tex
- report/preamb.tex
Create a section about overloading and generics within HCL.
- Added overloading section
- Added generics section
- HCLANG-62
- all other files [except in /code/] use …
> Hclang 62 explain generics and overloading

- misc/CFGs/HCLANG_EBNF.txt
- report/Appendix/0.AppendixCtrl.tex
Updated the two versions of EBNF (.txt file and report) to match each other
Please go through both grammars to make sure that everything is as it should be!
> Fix ebnf for master

- code/src/main/kotlin/exceptions/MissingArgumentError.kt
- code/src/main/kotlin/exceptions/MissingEncapsulationError.kt
- code/src/main/kotlin/exceptions/StringDoesntEndError.kt
- code/src/main/kotlin/exceptions/TypeError.kt
- code/src/main/kotlin/exceptions/UndeclaredError.kt
- code/src/main/kotlin/exceptions/UninitializedError.kt
- code/src/main/kotlin/exceptions/ZeroDivisionError.kt
- code/src/main/kotlin/lexer/Lexer.kt
- code/src/test/kotlin/lexicalTests/LexerTest.kt
- code/src/test/kotlin/loggerTests/LoggerTest.kt
> Fix for logger

- report/2.Analysis/HighOrderFunctions.tex
- report/3.Theory/LanguageSpecification.tex
- report/Appendix/0.AppendixCtrl.tex
Added section about high-order functionality, modified overloading section and updated syntax in some listings.
- Wrote section about high order functionality.
- Updated overloading section to match the new ":" operator for function passing.
- Updated syntax in some listings using an outdated syntax.
- Changed a listing a bit, to show the optional return for single expression lambda bodies.
- HCLANG-54
- It's always a good idea having another reviewer look at a PR as …
> Hclang 54 hof in hcl new

- code/src/test/kotlin/lexicalTests/LexerTest.kt
- report/2.Analysis/ProblemStatement.tex
Fixed the problem statement to make it more specific to our project problem
- Fixed problem statement
- Added test for negative values in Lexer.
- It's always a good idea having another reviewer look at a PR as well, if …
> Hclang 71 fix problem statement

- code/src/main/kotlin/parser/symboltable/ISymbolTable.kt
- report/2.Analysis/HighOrderFunctions.tex
- report/3.Theory/0.TheoryCtrl.tex
- report/3.Theory/SymbolTable.tex
An explanation of the symbol table interface and the design considerations it went through.
Added section concerning the symbol table.
- HCLANG-80
- Are there …
> Hclang 80 symbol table documentation

- report/1.Introduction/1.IntroductionCtrl.tex
- report/abbreviations.tex
Added HCL abbreviation to Abbreviations and introduced the abbreviation in the introduction.
PR into HCLANG 88 to avoid conflics
- Abbreviated abbriviation, added the abbreviation into abbreviations 
and introduced the abbreviation and its un-abbreviated form in to the introduction
- also abbreviation
- HCLANG-68
- Make sure this is ready for exams if this is going …
> HCL abbreviation added and presented in introduction

- code/build.gradle
- code/src/main/kotlin/builtins/HclBuiltinFunctions.kt
- code/src/main/kotlin/generation/SourceCodePrinter.kt
- code/src/main/kotlin/parser/AstNode.kt
- code/src/main/kotlin/parser/Parser.kt
- code/src/main/kotlin/parser/ParserWithoutBuiltins.kt
- code/src/test/kotlin/builtinTests/TestAllBuiltinsExist.kt
- code/src/test/kotlin/parserTests/FunctionCallTests.kt
- code/src/test/kotlin/parserTests/FunctionDeclarationTests.kt
- code/src/test/kotlin/parserTests/GenericsTests.kt
- code/src/test/kotlin/parserTests/ListTests.kt
- code/src/test/kotlin/parserTests/MiscellaneousTests.kt
- code/src/test/kotlin/parserTests/TupleTests.kt
- code/src/test/kotlin/parserTests/utils.kt
Added initial built in logic for our built in functions.
- Added initial built in logic for our built in functions.
- Added raw cpp command type
- Added tests along with testing framework spek.
- HCLANG-97
- It's always a good idea having another reviewer look at a PR as well, if it's major. get a …
> Hclang 97 initial builtin logic

- code/cppRawListDatastructure/arraylist.cpp
- code/cppRawListDatastructure/arraylist.h
new keyword might not be arduino compatible.
Added list shit
Move if you are not fond of the actual location
Just raw dump, haven't looked into if it has to go in code
- added list structure with:
bool contains(T item);
int indexof (T item);
int lastindexof (T item);
T get (int index);
int elementsInArray();
void add(T item);
void add(int index, T item);
void set(int index, T item);
void removeElementAt(int index);
void remove(T item);
- HCLANG-96
A small checklist of things to note when you are doing a review. Make sure these things apply before going into …
> Added arraylist datastucture (uses new keyword)

- code/src/main/kotlin/parser/Parser.kt
- code/src/main/kotlin/parser/typechecker/TypeChecker.kt
Added support for recursive calls in HCL.
- Added support for recursive calls in HCL.
- HCLANG-94 …
> Added support for recursion

- code/cppRawListDatastructure/ConstList.h
- code/cppRawListDatastructure/main.cpp
Added a constant list implementation in cpp
- Const list header
- main file with some tests for the list
This is an addition to
- HCLANG-96
- all other files [except in …
> Const list

- report/4.Solution/Lexer.tex
> fix lambeks lexer comments

- code/src/main/kotlin/builtins/HclBuiltinFunctions.kt
- code/src/main/kotlin/parser/AstNode.kt
- code/src/main/kotlin/parser/LambdaExpressionAttributes.kt
Added attributes for lambda expressions. These are very handy when doing code generation when some lambda expressions should be handled differently
- Added lambda expressions attributes class with a class for builtin and default lambda expressions.
- HCLANG-106
- It's always a good idea having another …
> Lambda attributes

- report/2.Analysis/ArduinoInEducation.tex
- report/2.Analysis/ArduinoLanguagesCtrl.tex
- report/2.Analysis/EducationalMiniComputers.tex
- report/2.Analysis/LanguagesForYoungPeople.tex
- report/2.Analysis/ProblemStatement.tex
- report/3.Theory/SyntaxTheory.tex
Fixed wills and various strange things I found.
Be sure to read this well, as I am bound to have made some errors.
Stuff 
(Sorry im useless
- HCLANG-100
- It's always a good idea having another reviewer look at a PR as well, if it's major. …
> Fixed wills and various booboos

- report/4.Solution/LanuageOfCompiler.tex
> Fix Kotlin is run where

- report/2.Analysis/LanguagesForYoungPeople.tex
- report/3.Theory/LanguageSpecification.tex
- report/4.Solution/ParserImplementation.tex
Fix for lambcreeks concerns/ requested changes for Release w18 pull request.
- this has changed
- this has aswell 
- which includes this
- and also this
- It's always a good idea having another reviewer look at a PR as …
> FixLamBcreekComments

- report/Appendix/0.AppendixCtrl.tex
Added precedence and generics rules in CFG
- HCLANG-67 …
> Added precedence and generics rules to CFG

- code/src/main/kotlin/builtins/HclBuiltinFunctions.kt
- report/4.Solution/BuiltInFunctions.tex
New PR because old one got merged to quickly
- shit got changed
- HCLANG-114
- all other files [except in …
> Lambek's changes

- report/3.Theory/LanguageSpecification.tex
Casa's table, because he is a bad boy
Added table
- HCLANG-93
- all other files [except in /code/] use …
> HCLANG-93-casatable

- report/3.Theory/LanguageSpecification.tex
- report/4.Solution/ParserImplementation.tex
Strange thing is, none of these are actually referenced anywhere.
Went through and fixed some repeating labels
These are not referenced in the text which is potentially an issue.
- It's always a good idea having another …
> Fixed some multiple defined labels

- report/3.Theory/SemanticsDescription.tex
- report/preamb.tex
Further fixed semantics, quite extensive, removed various parts
- Changed most procedure references
- changed string to txt
- did not add how list is represented in the implementation (does not have relevance)
- HCLANG-115
- It's always a …
> Hclang-115 Further fix semantics

- report/4.Solution/GeneratedCppCode.tex
- report/5.Conclusion/FutureWork.tex
- report/5.Conclusion/QualityAssurance.tex
Wrote a bit more future work, and a couple of fixes.
- this has changed
- this has aswell 
- which includes this
- and also this
- It's always a good idea having another reviewer look at a PR as well, if it's major. get a …
> Small fixes and further future work.

- report/2.Analysis/Scope.tex
- report/4.Solution/GeneratedCppCode.tex
- report/4.Solution/Parser.tex
- report/4.Solution/ParserImplementation.tex
- report/5.Conclusion/0.ConclusionCtrl.tex
- report/5.Conclusion/Discussion.tex
- report/5.Conclusion/QualityAssurance.tex
> Hclang 121 discussion

- report/5.Conclusion/Discussion.tex
Jeg rettede seriøst kun tre stavefejl, men den tror, at jeg har ændret hele filen
Jeg rettede linje 20, 46 og 60
> Tre ændringer, der ligner en hel masse

- report/5.Conclusion/Conclusion.tex
- report/5.Conclusion/Discussion.tex
> english->English, c++ -> bold

- report/2.Analysis/ProblemStatement.tex
- report/4.Solution/DesignOfCompiler.tex
- report/4.Solution/GeneratorClasses.tex
- report/5.Conclusion/Conclusion.tex
_**Please edit this to reflect the pull request. A pullr equest with this line in it will not(!!!) be accepted.**_
A short explaination of the pull request if needed. Could be "we added support for Python" or a long ass text. Ideally a few lines.
- this has changed
- this has aswell 
- which includes this
- and also this
- Comment anything that doesn't make sense or anything you want …
> Fix ya cyntinous inspirations

- report/3.Theory/SemanticsDescription.tex
Added the final semantic rules.
Semantics.
- HCLANG-139
- Are there testcases for new features / …
> HCLANG-139 to HandIn

- report/2.Analysis/ArduinoInEducation.tex
- report/2.Analysis/ArduinoLanguagesCtrl.tex
- report/2.Analysis/LanguagesForYoungPeople.tex
- report/3.Theory/LanguageSpecification.tex
- report/4.Solution/BuiltInFunctions.tex
- report/4.Solution/LanuageOfCompiler.tex
- report/4.Solution/Lexer.tex
- report/5.Conclusion/Conclusion.tex
- report/5.Conclusion/Discussion.tex
- report/5.Conclusion/FutureWork.tex
- report/Titelblad.tex
FixedC++ in report uses texttt now
- this has changed
- this has aswell 
- which includes this
- and also this
- all .tex …
> Fixedallthefucking c++

- report/4.Solution/GeneratorClasses.tex
removed ugly list, added small description instead …
> removed ugly list format - wrote small description instead

- code/src/main/kotlin/HCL.kt
- code/src/main/kotlin/builtins/HclBuiltinFunctions.kt
- code/src/main/kotlin/generation/IValidNameTranslator.kt
- code/src/main/kotlin/generation/cpp/CodeGenerator.kt
- code/src/main/kotlin/generation/cpp/CppNameTranslator.kt
- code/src/main/kotlin/generation/cpp/HelperHeaders.kt
- code/src/main/kotlin/generation/cpp/MainGenerator.kt
- code/src/main/kotlin/generation/cpp/Utils.kt
- code/src/main/kotlin/lexer/Token.kt
- code/src/main/kotlin/parser/AstNode.kt
- code/src/main/kotlin/parser/LambdaExpressionAttributes.kt
- code/src/main/kotlin/parser/Parser.kt
- code/src/main/kotlin/parser/ParserWithoutBuiltins.kt
- code/src/main/kotlin/parser/symboltable/ISymbolTable.kt
- code/src/main/kotlin/parser/symboltable/Symbol.kt
- code/src/main/kotlin/parser/typechecker/TypeChecker.kt
- code/src/main/kotlin/utils/BufferedLaabStream.kt
- code/src/main/kotlin/utils/ExecuteCommand.kt
- code/src/main/kotlin/utils/IBufferedLaabStream.kt
- code/src/main/resources/stdlib.hcl
Added many comments to code. Please say if comments are bad/some comments are missing/some comments are unnecessary
> Added many comments. Hopefully no comments where code is obvious

- code/src/main/kotlin/generation/cpp/TypeGenerator.kt
- code/src/test/kotlin/hclCodeTests/TestHclPrograms.kt
- code/src/test/resources/aTupleInFunction.hcl
Fixed: Tuple declarations in function bodies were not added to types.h
> Fixed how it didn't fetch tuple declarations from function bodies

- code/src/test/resources/testFirstIndexWhereStdlib.hcl
- report/3.Theory/SemanticsDescription.tex
> Fixes according to comments

- report/3.Theory/SemanticsDescription.tex
Fixed many typos and a few other errors in semantics
- Are there testcases for new features / methods?
- Have you tried running the source and tested things that …
> Semantics fix
